const ActionTypes = {
   USER_LIST:"USER_LIST",
   CURRENT_USER:"CURRENT_USER",
   CATEGORY_LIST:"CATEGORY_LIST",
   SELECTED_USER_FOR_MESSAGE:"SELECTED_USER_FOR_MESSAGE",
   MESSAGE_LIST:"MESSAGE_LIST"
}

export default ActionTypes

